const currencyList = [
  "USD - United States Dollar",
  "EUR - Euro",
  "JPY - Japanese Yen",
  "GBP - British Pound Sterling",
  "AUD - Australian Dollar",
  "CAD - Canadian Dollar",
  "CHF - Swiss Franc",
  "CNY - Chinese Yuan",
  "SEK - Swedish Krona",
  "NZD - New Zealand Dollar",
  "KRW - South Korean Won",
  "SGD - Singapore Dollar",
  "NOK - Norwegian Krone",
  "MXN - Mexican Peso",
  "INR - Indian Rupee",
  "RUB - Russian Ruble",
  "ZAR - South African Rand",
  "TRY - Turkish Lira",
  "BRL - Brazilian Real",
  "HKD - Hong Kong Dollar",
  "IDR - Indonesian Rupiah",
  "MYR - Malaysian Ringgit",
  "PHP - Philippine Peso",
  "CZK - Czech Republic Koruna",
  "PLN - Polish Zloty",
  "THB - Thai Baht",
  "HUF - Hungarian Forint",
  "DKK - Danish Krone",
  "ISK - Icelandic Krona",
  "HRK - Croatian Kuna",
  "ILS - Israeli New Shekel",
  "CLP - Chilean Peso",
  "ARS - Argentine Peso",
  "TWD - New Taiwan Dollar",
  "SAR - Saudi Riyal",
  "AED - United Arab Emirates Dirham",
  "COP - Colombian Peso",
  "EGP - Egyptian Pound",
  "NPR - Nepalese Rupee",
  "PKR - Pakistani Rupee",
  "KWD - Kuwaiti Dinar",
  "KES - Kenyan Shilling",
  "VND - Vietnamese Dong",
  "BDT - Bangladeshi Taka",
  "DZD - Algerian Dinar",
  "RON - Romanian Leu",
  "UGX - Ugandan Shilling",
  "LKR - Sri Lankan Rupee",
  "UGX - Ugandan Shilling",
  "GHS - Ghanaian Cedi",
  "BGN - Bulgarian Lev",
  "IQD - Iraqi Dinar",
  "OMR - Omani Rial",
  "QAR - Qatari Rial",
  "PEN - Peruvian Nuevo Sol",
  "BDT - Bangladeshi Taka",
  "VND - Vietnamese Dong",
  "IRR - Iranian Rial",
  "XOF - West African CFA Franc",
  "TZS - Tanzanian Shilling",
  "NGN - Nigerian Naira",
  "BYN - Belarusian Ruble",
  "LBP - Lebanese Pound",
  "CUP - Cuban Peso",
  "XAF - Central African CFA Franc",
  "GEL - Georgian Lari",
  "AMD - Armenian Dram",
  "MAD - Moroccan Dirham",
  "NAD - Namibian Dollar",
  "AFN - Afghan Afghani",
  "YER - Yemeni Rial",
  "MNT - Mongolian Tugrik",
  "CRC - Costa Rican Colon",
  "DOP - Dominican Peso",
  "MUR - Mauritian Rupee",
  "BHD - Bahraini Dinar",
  "LYD - Libyan Dinar",
  "SDG - Sudanese Pound",
  "MZN - Mozambican Metical",
  "AZN - Azerbaijani Manat",
  "BAM - Bosnia-Herzegovina Convertible Mark",
  "AWG - Aruban Florin",
  "JMD - Jamaican Dollar",
  "ANG - Netherlands Antillean Guilder",
  "XPF - CFP Franc",
  "SYP - Syrian Pound",
  "GYD - Guyanaese Dollar",
  "BBD - Barbadian Dollar",
  "SRD - Surinamese Dollar",
  "BND - Brunei Dollar",
  "LAK - Laotian Kip",
  "MWK - Malawian Kwacha",
  "ETB - Ethiopian Birr",
  "ERN - Eritrean Nakfa",
  "MOP - Macanese Pataca",
  "UGX - Ugandan Shilling",
  "ZMW - Zambian Kwacha",
  "CVE - Cape Verdean Escudo",
  "BSD - Bahamian Dollar",
  "HTG - Haitian Gourde",
  "GMD - Gambian Dalasi",
  "KZT - Kazakhstani Tenge",
  "SLL - Sierra Leonean Leone",
  "KYD - Cayman Islands Dollar",
  "PGK - Papua New Guinean Kina",
  "MVR - Maldivian Rufiyaa",
  "LSL - Lesotho Loti",
  "TJS - Tajikistani Somoni",
  "SCR - Seychellois Rupee",
  "GIP - Gibraltar Pound",
  "XCD - East Caribbean Dollar",
  "NIO - Nicaraguan Cordoba",
  "BZD - Belize Dollar",
  "FKP - Falkland Islands Pound",
  "GGP - Guernsey Pound",
  "IMP - Isle of Man Pound",
  "JEP - Jersey Pound",
  "SVC - Salvadoran Colon",
  "TMT - Turkmenistani Manat",
  "BTN - Bhutanese Ngultrum",
  "WST - Samoan Tala",
  "CUC - Cuban Convertible Peso",
  "ZWL - Zimbabwean Dollar",
  "CNH - Chinese Yuan (Offshore)",
  "SSP - South Sudanese Pound",
];

export default currencyList;
