const searchPathOptions = [
  { routes: "/find-creators", label: "Find Creators" },
  { routes: "/talent-profile", label: "Talent Profile" },
  { routes: "/pricing", label: "Pricing" },
  { routes: "/resources", label: "Resources" },
  { routes: "/talent-signup", label: "Talent Sign Up" },
  { routes: "/brand-firstGig", label: "Brand Sign Up" },
  { routes: "/about-us", label: "About" },
  { routes: "/community-guidelines", label: "Guidelines" },
  { routes: "/blogs", label: "Blogs" },
  { routes: "/post-job", label: "PostJob" },
  { routes: "/how-it-works", label: "How It Works" },
  { routes: "/login", label: "Login" },
  { routes: "/job-list", label: "Overall Jobs" },
  //   { routes: "/login", label: "Forgot Password" },
  { routes: "/talent-dashboard", label: "Talent Dashboard" },
  { routes: "/brand-dashboard", label: "Brand Home" },
  { routes: "/list-jobs", label: "List Jobs" },
  { routes: "/applied-jobs", label: "Applied Jobs" },
  { routes: "/saved-jobs", label: "Saved Jobs" },
  { routes: "/create-jobs", label: "Create Jobs" },
  { routes: "/find-talents", label: "Brand Talents" },
  { routes: "/favorite-talents", label: "Brand Favorites" },
  { routes: "/brand-help", label: "Brand Help" },
  { routes: "/applicants", label: "Applicants" },
  { routes: "/edit-talent-profile", label: "Edit Talent" },
  { routes: "/edit-brand-profile", label: "Edit Brands" },
  { routes: "/talent-notification", label: "Talent Notification" },
  { routes: "/talent-settings", label: "Talent Settings" },
  { routes: "/brand-settings", label: "Brand Settings" },
  { routes: "/talent-home", label: "Talent Home" },
  { routes: "/talent-help", label: "Talent Help" },
  { routes: "/brand-notification", label: "Brand Notification" },
  { routes: "/get-booked", label: "Get Booked" },
];

export default searchPathOptions;
